### ISSUE TITLE
no detections for 

### ISSUE THREAD

**Issue by wangyd-0312** [aleksandrkim61/EagerMOT#29]
hello, thank you for your work!
I have tried to train EagerMOT with center point and mmdetection, but I got this error. Could you give some help?

```
Parsing NuScenes v1.0-mini ...
======
Loading NuScenes tables for version v1.0-mini...
23 category,
8 attribute,
4 visibility,
911 instance,
12 sensor,
120 calibrated_sensor,
31206 ego_pose,
8 log,
10 scene,
404 sample,
31206 sample_data,
18538 sample_annotation,
4 map,
Done loading in 0.360 seconds.
======
Reverse indexing ...
Done reverse indexing in 0.1 seconds.
======
Done parsing
Starting sequence: scene-0061
Processing frame ca9a282c9e77460f8360f564131a8af5
Parsing /home/zxl/wyd_EagerMOT/EagerMOT-open_main/centerpoint/mini_train/detections1.json
Traceback (most recent call last):
  File "run_tracking.py", line 176, in <module>
    run_on_nuscenes()
  File "run_tracking.py", line 151, in run_on_nuscenes
    mot_dataset, NUSCENES_BEST_PARAMS, target_sequences, sequences_to_exclude)
  File "run_tracking.py", line 131, in perform_tracking_with_params
    sequences_to_exclude=sequences_to_exclude)
  File "run_tracking.py", line 40, in perform_tracking_full
    run_info = sequence.perform_tracking_for_eval(params)
  File "/home/zxl/wyd_EagerMOT/EagerMOT-open_main/dataset_classes/mot_sequence.py", line 73, in perform_tracking_for_eval
    predicted_instances = frame.perform_tracking(params, run_info)
  File "/home/zxl/wyd_EagerMOT/EagerMOT-open_main/dataset_classes/mot_frame.py", line 166, in perform_tracking
    self.fuse_instances_and_save(params, run_info, load=False, save=False)
  File "/home/zxl/wyd_EagerMOT/EagerMOT-open_main/dataset_classes/mot_frame.py", line 66, in fuse_instances_and_save
    self.bboxes_3d, self.dets_2d_multicam, params["fusion_iou_threshold"])
  File "/home/zxl/wyd_EagerMOT/EagerMOT-open_main/dataset_classes/mot_frame.py", line 247, in dets_2d_multicam
    self.load_segmentations_2d_if_needed()
  File "/home/zxl/wyd_EagerMOT/EagerMOT-open_main/dataset_classes/mot_frame.py", line 224, in load_segmentations_2d_if_needed
    dets_2d_multicam = self.sequence.get_segmentations_for_frame(self.name)
  File "/home/zxl/wyd_EagerMOT/EagerMOT-open_main/dataset_classes/mot_sequence.py", line 93, in get_segmentations_for_frame
    self.dets_2d_multicam_per_frame = self.load_detections_2d()
  File "/home/zxl/wyd_EagerMOT/EagerMOT-open_main/dataset_classes/nuscenes/sequence.py", line 82, in load_detections_2d
    frames_cam_tokens_detections = loading.load_detections_2d_nuscenes(self.seg_source, self.token)
  File "/home/zxl/wyd_EagerMOT/EagerMOT-open_main/inputs/loading.py", line 100, in load_detections_2d_nuscenes
    return detections_2d.load_detections_2d_mmdetection_nuscenes(seq_name)
  File "/home/zxl/wyd_EagerMOT/EagerMOT-open_main/inputs/detections_2d.py", line 101, in load_detections_2d_mmdetection_nuscenes
    all_dets = utils.load_json_for_sequence(utils.DETECTIONS_MMDETECTION_CASCADE_NUIMAGES_NUSCENES, seq_name)
  File "/home/zxl/wyd_EagerMOT/EagerMOT-open_main/inputs/utils.py", line 151, in load_json_for_sequence
    raise NotADirectoryError(f"No detections for {target_seq_name}")
NotADirectoryError: No detections for cc8c0bf57f984915a77078b10eb33198


```

**Comment by aleksandrkim61** [comment]
Did you use the provided detections or generate yourself? The script expects detections for all key frames. Check what this sequence is and if it is correctly generated

Closing for now
